alias open="nautilus"
alias ping="ping -O"
alias ping1="ping sgp-1.valve.net"
alias pingml="ping 222.127.12.131"
alias youtubedl-video="youtube-dl -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4' --external-downloader aria2c"
alias gitlogprettify="git log --all --decorate --oneline --graph"
alias lg1="git log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(bold yellow)%d%C(reset)' --all"
alias gitlog="git log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold cyan)%aD%C(reset) %C(bold green)(%ar)%C(reset)%C(bold yellow)%d%C(reset)%n'' %C(white)%s%C(reset) %C(dim white)- %an%C(reset)' --all"
alias today="echo $(date '+%b-%d-%Y-%a')"
alias mklog="vim $(today).txt"
# alias modlog="vim $(today).txt"
alias viewlog="cat $(today).txt"
alias getip="curl ipinfo.io/ip"
alias untar="tar -zxvf "
alias mkpass="openssl rand -base64 20"
alias dirsize="du -sh"
alias subdirsize="du -h --max-depth=1 | sort -hr" # get all folder sizes sorted
